In [1]:
import torch

In [2]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [3]:
x = x.reshape([3, 4])
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [4]:
torch.zeros(1, 2, 3)

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

In [5]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [6]:
torch.tensor([1.2, 3.9], dtype=torch.int32)

tensor([1, 3], dtype=torch.int32)

In [7]:
torch.cat((x, y), dim=0)

tensor([1., 2., 4., 8., 2., 2., 2., 2.])

In [8]:
x[None]

tensor([[1., 2., 4., 8.]])

In [9]:
torch.cat((x[None], y[None]), dim=0)

tensor([[1., 2., 4., 8.],
        [2., 2., 2., 2.]])

In [10]:
torch.cat((x[:, None], y[:, None]), dim=1)

tensor([[1., 2.],
        [2., 2.],
        [4., 2.],
        [8., 2.]])

In [11]:
x = torch.arange(12, dtype=torch.float32).reshape((3, 2, 2))
x

tensor([[[ 0.,  1.],
         [ 2.,  3.]],

        [[ 4.,  5.],
         [ 6.,  7.]],

        [[ 8.,  9.],
         [10., 11.]]])

In [12]:
x.sum(dim=0), x.sum(dim=[0, 1]), x.sum()

(tensor([[12., 15.],
         [18., 21.]]),
 tensor([30., 36.]),
 tensor(66.))

In [13]:
X = torch.tensor([1, 2, 3])
Y = torch.tensor([4, 5, 6])

In [14]:
# inplace operation (saving memory)
Z = torch.zeros_like(Y)
before = id(Z)
Z[:] = X + Y
id(Z) == before

True

In [15]:
# not inplace operation
Z = torch.zeros_like(Y)
before = id(Z)
Z = X + Y
id(Z) == before

False

In [16]:
I = torch.tensor([3.14])
I.item(), float(I), int(I)

(3.140000104904175, 3.140000104904175, 3)